# Generated by Django 4.0.6 on 2022-08-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_usInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guest_card_img/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='StatisticInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование статуса')),
                ('href', models.CharField(max_length=100, verbose_name='Ссылка на иконку')),
                ('value', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Type_ofCompanions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100, verbose_name='Тип заведения')),
                ('tag', models.CharField(max_length=100, verbose_name='html-тэг')),
            ],
            options={
                'verbose_name': 'Тип заведения',
                'verbose_name_plural': 'Типы заведений',
            },
        ),
        migrations.CreateModel(
            name='Companions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование заведения')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='Статус заведения')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guest_card_img/', verbose_name='Фотография')),
                ('href', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('type_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_main.type_ofcompanions', verbose_name='Тип заведения')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
                'ordering': ['type_of'],
            },
        ),
    ]
