# Generated by Django 4.0.6 on 2022-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticinfo',
            name='href',
            field=models.CharField(max_length=50, verbose_name='Ссылка на иконку'),
        ),
        migrations.AlterField(
            model_name='statisticinfo',
            name='value',
            field=models.CharField(max_length=11, verbose_name='Ссылка на Количество'),
        ),
    ]
