# Generated by Django 4.0.2 on 2022-08-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_main', '0002_alter_statisticinfo_href_alter_statisticinfo_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticinfo',
            name='cent',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='companions',
            name='status',
            field=models.FloatField(blank=True, null=True, verbose_name='Статус заведения'),
        ),
        migrations.AlterField(
            model_name='statisticinfo',
            name='value',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
