# Generated by Django 4.1 on 2022-08-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_main', '0003_statisticinfo_cent_alter_companions_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_usinfo',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='about_usinfo',
            name='description_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='about_usinfo',
            name='description_uz',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companions',
            name='description_en',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companions',
            name='description_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companions',
            name='description_uz',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companions',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование заведения'),
        ),
        migrations.AddField(
            model_name='companions',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование заведения'),
        ),
        migrations.AddField(
            model_name='companions',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование заведения'),
        ),
        migrations.AddField(
            model_name='statisticinfo',
            name='cent_en',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='statisticinfo',
            name='cent_ru',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='statisticinfo',
            name='cent_uz',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='statisticinfo',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование статуса'),
        ),
        migrations.AddField(
            model_name='statisticinfo',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование статуса'),
        ),
        migrations.AddField(
            model_name='statisticinfo',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование статуса'),
        ),
        migrations.AddField(
            model_name='type_ofcompanions',
            name='types_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип заведения'),
        ),
        migrations.AddField(
            model_name='type_ofcompanions',
            name='types_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип заведения'),
        ),
        migrations.AddField(
            model_name='type_ofcompanions',
            name='types_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип заведения'),
        ),
        migrations.AlterField(
            model_name='companions',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
