# Generated by Django 4.1 on 2022-08-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_main', '0004_about_usinfo_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Hubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50, verbose_name='Ссылка на иконку')),
                ('href', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Соц.сеть',
                'verbose_name_plural': 'Соц.сети',
            },
        ),
    ]
